"""Explore candidate models over a small grid and (optionally) promote the winner.

Run it to compare estimators on held-out RMSE; pass ``--write-best model_training/
champion.yaml`` to serialize the lowest-RMSE config into the champion file that CD
trains from. Promotion then lands as a reviewed diff to that file.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from model_training.config import TrainingConfig
from model_training.train import train

GRID: list[dict[str, Any]] = [
    {"model_type": "linear_regression", "model_params": {}},
    {"model_type": "ridge", "model_params": {"alpha": 0.5}},
    {"model_type": "ridge", "model_params": {"alpha": 5.0}},
    {"model_type": "random_forest", "model_params": {"n_estimators": 200, "max_depth": 10}},
    {
        "model_type": "gradient_boosting",
        "model_params": {"learning_rate": 0.05, "n_estimators": 300},
    },
]

# Fields written to the champion file -- the modeling decision plus the frozen data/split
# knobs. Paths and the rmse gate are deliberately excluded (CD supplies those).
CHAMPION_FIELDS = (
    "model_type",
    "model_params",
    "currency",
    "min_price",
    "max_price",
    "reference_year",
    "test_size",
    "random_state",
    "min_category_frequency",
)


def write_champion(config: TrainingConfig, path: Path) -> None:
    import yaml

    payload = {name: getattr(config, name) for name in CHAMPION_FIELDS}
    header = (
        "# Champion model config -- generated by `sweep.py --write-best`.\n"
        "# Review and commit this file to promote the model (see model_training/champion.yaml).\n"
    )
    path.write_text(header + yaml.safe_dump(payload, sort_keys=False))


def main() -> None:
    parser = argparse.ArgumentParser(description="Sweep candidate models and pick the best.")
    parser.add_argument(
        "--write-best",
        type=Path,
        default=None,
        help="If set, write the lowest-RMSE config to this YAML path (e.g. "
        "model_training/champion.yaml) for review + promotion.",
    )
    args = parser.parse_args()

    best_config: TrainingConfig | None = None
    best_rmse = float("inf")
    for overrides in GRID:
        config = TrainingConfig(**overrides)
        result = train(config)
        test_metrics = result["metrics"]["test"]
        print(config.model_type, overrides.get("model_params"), test_metrics)
        if test_metrics["rmse"] < best_rmse:
            best_rmse, best_config = test_metrics["rmse"], config

    assert best_config is not None  # GRID is non-empty
    print(f"\nBest: {best_config.model_type} {best_config.model_params} (rmse={best_rmse:.2f})")
    if args.write_best:
        write_champion(best_config, args.write_best)
        print(f"Wrote champion config -> {args.write_best}")


if __name__ == "__main__":
    main()
